<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.26.300" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.16" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DynamicTransaction\DynamicTransaction.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ConnectionDll">
      <HintPath>Data\ExternalSources\ConnectionDll.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
